# Dependencies
markdown:         kramdown
redcarpet:
  extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Leigh Hires Turner
tagline:          ''
# url:              http://leighhiresturner.com
# shorturl:         leighhiresturner.com

author:
  name:           'Clay Carson'
  url:            https://twitter.com/turnerthornton

paginate:         10
paginate_path: "/archives/page/:num"

# Custom vars
version:          1.0.0

github:
  repo:           github.com/turnerthornton/turnerthornton.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  Home: '/index.html/'
  Cover Letter: '/cover-letter/'
  Resume: '/resume/'
  


